server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
      url: jdbc:mysql://localhost:3308/cardsdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
# always try to execute the scripts that I have mentioned inside the schema.sql
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"

#build:
#  version: "3.0"
#
#cards:
#  message: "Welcome to EasyBank cards related local APIs"
#  contactDetails:
#    name" : "Bao Nguyen"
#    email: "nguyenducbaokey@gmail.com"
#  onCallSupport:
#    - (+84) 788 049 042
#    - (+84) 123 456 789
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        # spring boot actuator will enable and expose all management endpoint and inside these endpoints only we are also going to have refresh related endpoint.
        include: "*"
