apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-definitions
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "guest",
          "password": "guest",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }