pipeline {
    agent any

    stages {
        stage('Build Jar') {
            agent {
                docker {
                    image 'maven:3.8.3-openjdk-17'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ls -la
                    mvn -version
                    mvn -f Accounts/pom.xml clean install
                '''
            }
        }
        stage('Build image') {
            steps {
                sh '''
                 # get current day in yyMMdd
                TAG=$(date +'%y%m%d')
                echo "Building Docker image with tag: $TAG"
                docker build -f Accounts/Dockerfile Accounts -t baotuyloan1/accounts:$TAG
                '''
            }
        }
    }
}
