deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1
image:
  repository: baotuyloan1/configserver
  tag: 250130

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resource_enabled: false
otel_enabled: false
kafka_enabled: false


datasource_enabled: false
datasource_root_password: root
database_enabled: false
mysqlDatabase: cardsdb
springDatasourceUsername: root
springDatasourcePassword:  root
datasourceUrl: jdbc:mysql://cardsdb:3306