services:
  accounts:
    image: baotuyloan1/accounts:241114
#    if you don't provide container_name, a random name will given to your container by the Docker server
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          # I just want to allocate maximum 700M of memory
          memory: 700M
    networks:
      - easybank
  loans:
    image: baotuyloan1/loans:241115
    #    if you don't provide container_name, a random name will given to your container by the Docker server
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          # I just want to allocate maximum 700M of memory
          memory: 700M
    networks:
      - easybank
  cards:
    image: baotuyloan1/cards:241115
    #    if you don't provide container_name, a random name will given to your container by the Docker server
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          # I just want to allocate maximum 700M of memory
          memory: 700M
    networks:
      - easybank
    # we create a network with the name easybank and the driver is bridge.
    # the reason why we need to create a network is because we want to make sure all our containers are able to communicate with each other.
    # we give the name easybank to the network so that we can use this network name.
networks:
  easybank:
    driver: "bridge"