apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "admin-user" # Crete a secret for the admin user that we have created in dashboard-adminuser.yaml
type: kubernetes.io/service-account-token