spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"



#  spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #    for liveness and readiness probes
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  #      enable endpoint for readiness and liveness
  endpoint:
    health:
      probes:
        enabled: true
  #        groups all metrics related to the microservice under the application name
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    com:
      baond:
        eurekaserver: DEBUG
  pattern:
    #    five characters for some log severity (info, warn, error)
    # after the tag information, convey to my spring boot framework at runtime Open Telemetry library is going to generate the trace ID with the context information.
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"