spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"



#  spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #    for liveness and readiness probes
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  #      enable endpoint for readiness and liveness
  endpoint:
    health:
      probes:
        enabled: true
  #        groups all metrics related to the microservice under the application name
  metrics:
    tags:
      application: ${spring.application.name}