deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1
image:
  repository: baotuyloan1/loans
  tag: 250130

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resource_enabled: false
otel_enabled: true
kafka_enabled: false
