deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1
image:
  repository: baotuyloan1/cards
  tag: 250130

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resource_enabled: false
otel_enabled: true
kafka_enabled: false
