spring:
  application:
    name: "configserver"
  profiles:
#     whenever we are trying to use a classpath to store all our configuration,
#    we need to make sure we are activating this native profile
    active: native
  cloud:
    config:
      server:
#        we need to mention native because we activated the native profile
        native:
#          reading configurations from a file system location.
          search-locations: "file:///D://CODE//CODING//BE//Spring//Microservices//DemoForEasyBanking//propertiesConfig"
#          reading configurations from the classpath location of Config server
#          search-locations: "classpath:/config"

server:
  port: 8071