deploymentName: cardsdb-deployment
serviceName: cardsdb
appLabel: cardsdb
appName: cardsdb

replicaCount: 1
image:
  repository: mysql
  tag: latest

containerPort: 3306

service:
  type: LoadBalancer
  port: 3308
  targetPort: 3306

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resource_enabled: false
otel_enabled: false
kafka_enabled: false


datasource_enabled: false
datasource_root_password: root
database_enabled: true
mysqlDatabase: cardsdb
springDatasourceUsername: root
springDatasourcePassword:  root
datasourceUrl: jdbc:mysql://accountsdb:3306/accountsdb