deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 2
image:
  repository: baotuyloan1/eurekaserver
  tag: 250130

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resource_enabled: false
otel_enabled: true
kafka_enabled: false

datasource_enabled: false
datasource_root_password: root
database_enabled: false
mysqlDatabase: cardsdb
springDatasourceUsername: root
springDatasourcePassword:  root
datasourceUrl: jdbc:mysql://cardsdb:3306