apiVersion: v1
kind: ConfigMap
metadata:
  name: easybank-configmap
data: # at this data element, we can provide any number of environment properties with a key and value.
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
  ACCOUNTS_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
  LOANS_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
  CARDS_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  LOANS_APPLICATION_NAME: "loans"
  CARDS_APPLICATION_NAME: "cards"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"