deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts


replicaCount: 2
image:
  repository: baotuyloan1/accounts
  tag: 250130

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resource_enabled: false
otel_enabled: true
kafka_enabled: true

datasource_enabled: true
datasource_root_password: root
database_enabled: false
mysqlDatabase: accountsdb
springDatasourceUsername: root
springDatasourcePassword:  root
datasourceUrl: jdbc:mysql://accountsdb:3306/accountsdb