services:
  network-deploy-service:
    networks:
      - easybank
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          # I just want to allocate maximum 700M of memory
          memory: 700M
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"