apiVersion: 1
# delete any existing data sources with the names below
deleteDatasource:
  - name: Loki
  - name: Prometheus
  - name: Tempo
datasources:
  - name: Prometheus
    type: prometheus
#    unique id for this connection
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false # disable all authentications
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"